apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: my-crossplane-bucket-test
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-east-1
  providerConfigRef:
    name: aws-provider