apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
  namespace: argocd
  labels:
    app.kubernetes.io/instance: crossplane-app
spec:
  project: default
  source:
    repoURL: https://github.com/JerebChase/gitops-config.git
    targetRevision: main
    path: argocd/crossplane-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true