apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-config
spec:
  generators:
    - git:
        repoURL: https://github.com/JerebChase/gitops-config.git
        revision: main
        directories:
          - path: argocd/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/JerebChase/gitops-config.git
        targetRevision: main
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true