apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crossplane-namespace.yaml

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.19.0
    namespace: crossplane-system

namespace: crossplane-system