apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.12.2
- argocd-namespace.yml

patches:
- path: argocd-cm-patch.yml
- path: argocd-server-patch.yml

namespace: argocd