apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.12.2
- argocd-namespace.yaml

patches:
- path: argocd-cm-patch.yaml
- path: argocd-server-patch.yaml

namespace: argocd