apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//stable/manifests/install.yaml
- argocd-namespace.yml

patches:
- path: argocd-cm-patch.yml
- target:
    group: ""
    version: v1
    kind: Service
    name: argocd-server
    namespace: argocd
  patch: |-
    - op: replace
      path: "/spec/type"
      value: "LoadBalancer"

namespace: argocd